import React from 'react';
import Header from '../components/Header';
import Footer from '../components/footer';
import '../styles/affiliate.css';
import Lottie from 'react-lottie';
import animationData from '../assets/Animations/affiliate.json';
import '../styles/hero1.css'


function Affiliate()
{
    const defaultOptions = {
        loop: true,
        autoplay: true,
        animationData: animationData,
        rendererSettings: {
          preserveAspectRatio: 'xMidYMid slice'
        }
    };

    return (
        <>
        <Header></Header>
        <div className='affiliate_section'>
            <div className='titles_1'>
                <h1 className='heading'>Affiliate <span className='highlight'>Program</span></h1>
                <p className='bio'>Earn commissions by referring new customers to our platform.</p>
            </div>
            <div className='context'>
                <div className='affiliate_card_1'>
                    <h1 className='heading'>7% <span className='highlight'>Commission</span></h1>
                    <p className='bio'>Earn 7% commission on all sales generated by your referrals.</p>
                    <button>Level 1</button>
                </div>
                <div className='affiliate_card_2'>
                    <h1 className='heading'>3% <span className='highlight'>Commission</span></h1>
                    <p className='bio'>Earn 3% commission on all sales generated by your referrals' referrals.</p>
                    <button>Level 2</button>
                </div>
                <div className='affiliate_card_3'>
                    <h1 className='heading'>1%  <span className='highlight'>Commission</span></h1>
                    <p className='bio'>Earn 1% commission on all sales generated by your referrals' referrals' referrals.</p>
                    <button>Level 3</button>
                </div>
            </div>
            <div className='titles_2'>
                <h1 className='heading'>Earn from Referrals</h1>
                <p className='bio'>No deposit required. Earn commissions by sharing your unique referral link and promotional tools.</p>
                <button>Join Now</button>
                <div  className='containerStyle'>
                    <Lottie options={defaultOptions}/>
                </div>
            </div>
        </div>
        
        <Footer></Footer>
        </>
    ); 
}


export default Affiliate;